SEGUNDOS= input("INGRESE CANTIDAD DE SEGUNDOS:")
SEGUNDOS= int(SEGUNDOS)
HORAS=SEGUNDOS // 3600
SOBRANTE1=SEGUNDOS%3600
MINUTOS=SOBRANTE1//60
SOBRANTE2=SOBRANTE1%60
print("Horas:", HORAS)
print("Minutos", MINUTOS)
print("Segundos", SEGUNDOS)

